# This workflow will run headful and headless e2e tests.

name: E2E tests

on:
  pull_request:
  push:
    branches: 'main'

jobs:
  e2e:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        headful-argument: [headful, headless]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Google Chrome Dev/Unstable
        id: chrome
        uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: chrome
          version: dev
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install and build npm dependencies
        run: npm ci
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      - name: Run e2e tests
        if: runner.os == 'Linux'
        run: PUPPETEER_EXECUTABLE_PATH="$(which google-chrome-unstable)" xvfb-run --auto-servernum npm run e2e-${{ matrix.headful-argument }}
      - name: Run e2e tests
        if: runner.os == 'macOS'
        run: PUPPETEER_EXECUTABLE_PATH="${{ steps.chrome.outputs.path }}/${{ steps.chrome.outputs.binary }}" npm run e2e-${{ matrix.headful-argument }}

env:
  FORCE_COLOR: 3
